inputs_def:
  - handle: json
    json_schema:
      {}
    value: ""
  - group: more
    collapsed: true
  - handle: indent
    description: If it is 0, there is no carriage return and indentation. If it is
      greater than 0, there is a carriage return, and the number of spaces for
      indentation is the same as this number.
    json_schema:
      type: integer
      minimum: 0
    value: 0
    nullable: false
  - handle: ensure_ascii
    description: If on, all characters are ASCII (non-ASCII characters are escaped).
    json_schema:
      type: boolean
    value: false
outputs_def:
  - handle: string
    description: Output
    json_schema:
      type: string
ui:
  default_width: 395.15625
executor:
  name: python
  options:
    spawn: false
    entry: main.py
title: Stringify JSON
