executor:
  name: python
  options:
    entry: main.py
    spawn: false
inputs_def:
  - handle: binary
    json_schema:
      contentMediaType: oomol/bin
  - handle: encoding
    json_schema:
      enum:
        - utf8
        - ascii
        - hex
      ui:options:
        labels:
          - UTF-8
          - ASCII
          - HEX
    value: utf8
outputs_def:
  - handle: string
    json_schema:
      type: string
title: Decode string
